tinyurl.com/data-preprocess

import libraries

In [7]:
import numpy as np

In [8]:
import matplotlib.pyplot as plt
import pandas as pd

import the dataset

In [9]:
dataset=pd.read_csv('Data.csv')
dataset

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [10]:
type(dataset)

pandas.core.frame.DataFrame

Handling missing values
1. for continuous columns null values are filled with mean(normal distribution) or median(skew distribution)
2. For Categorical columns null values filled with mode.
3. According to industrial standards is there less than 5 % null values will drop the null value rows.

In [12]:
dataset.isnull().any()

Country      False
Age           True
Salary        True
Purchased    False
dtype: bool

In [13]:
dataset.isnull().sum()

Country      0
Age          1
Salary       1
Purchased    0
dtype: int64

In [14]:
dataset[dataset['Age'].isnull()].index.tolist()

[6]

In [15]:
dataset[dataset['Salary'].isnull()].index.tolist()

[4]

In [17]:
dataset['Salary'].fillna(dataset["Salary"].mean(),inplace=True)

In [19]:
dataset['Age'].fillna(dataset["Age"].mean(),inplace=True)

In [20]:
dataset

Country        Age        Salary Purchased
0   France  44.000000  72000.000000        No
1    Spain  27.000000  48000.000000       Yes
2  Germany  30.000000  54000.000000        No
3    Spain  38.000000  61000.000000        No
4  Germany  40.000000  63777.777778       Yes
5   France  35.000000  58000.000000       Yes
6    Spain  38.777778  52000.000000        No
7   France  48.000000  79000.000000       Yes
8  Germany  50.000000  83000.000000        No
9   France  37.000000  67000.000000       Yes

In [21]:
dataset['Age'] = dataset["Age"].round()

In [22]:
dataset

Country   Age        Salary Purchased
0   France  44.0  72000.000000        No
1    Spain  27.0  48000.000000       Yes
2  Germany  30.0  54000.000000        No
3    Spain  38.0  61000.000000        No
4  Germany  40.0  63777.777778       Yes
5   France  35.0  58000.000000       Yes
6    Spain  39.0  52000.000000        No
7   France  48.0  79000.000000       Yes
8  Germany  50.0  83000.000000        No
9   France  37.0  67000.000000       Yes

In [23]:
dataset.isnull().any()

Country      False
Age          False
Salary       False
Purchased    False
dtype: bool

separting dependent and independent variables

In [36]:
x=dataset.iloc[:,0:3].values
x

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 39.0, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [37]:
y=dataset.iloc[:,-1:].values
y

array([['No'],
       ['Yes'],
       ['No'],
       ['No'],
       ['Yes'],
       ['Yes'],
       ['No'],
       ['Yes'],
       ['No'],
       ['Yes']], dtype=object)

In [38]:
x.ndim

2

In [39]:
y.ndim

2

Encoding categorical text variables

In [40]:
dataset["Country"].value_counts()

France     4
Germany    3
Spain      3
Name: Country, dtype: int64

In [41]:
x.shape

(10, 3)

In [42]:
import sklearn

In [43]:
sklearn.__version__

'0.22.1'

In [44]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [47]:
ct = ColumnTransformer([("on",OneHotEncoder(),[0])],remainder="passthrough") 
x = ct.fit_transform(x)
x
'''
ct = ColumnTransformer([("on",OneHotEncoder(),[0])],remainder="passthrough") 
x = ct.fit_transform(x)
x
'''
##columntransformation accept values in list, in that will pass the objects in tuple
#0 represent the column number

array([[1.0, 0.0, 0.0, 44.0, 72000.0],
       [0.0, 0.0, 1.0, 27.0, 48000.0],
       [0.0, 1.0, 0.0, 30.0, 54000.0],
       [0.0, 0.0, 1.0, 38.0, 61000.0],
       [0.0, 1.0, 0.0, 40.0, 63777.77777777778],
       [1.0, 0.0, 0.0, 35.0, 58000.0],
       [0.0, 0.0, 1.0, 39.0, 52000.0],
       [1.0, 0.0, 0.0, 48.0, 79000.0],
       [0.0, 1.0, 0.0, 50.0, 83000.0],
       [1.0, 0.0, 0.0, 37.0, 67000.0]], dtype=object)

In [49]:
#Removing dummy variables
x=x[:,1:]

In [50]:
x

array([[0.0, 0.0, 44.0, 72000.0],
       [0.0, 1.0, 27.0, 48000.0],
       [1.0, 0.0, 30.0, 54000.0],
       [0.0, 1.0, 38.0, 61000.0],
       [1.0, 0.0, 40.0, 63777.77777777778],
       [0.0, 0.0, 35.0, 58000.0],
       [0.0, 1.0, 39.0, 52000.0],
       [0.0, 0.0, 48.0, 79000.0],
       [1.0, 0.0, 50.0, 83000.0],
       [0.0, 0.0, 37.0, 67000.0]], dtype=object)

In [51]:
x.shape

(10, 4)

In [57]:
from sklearn.preprocessing import LabelEncoder
lb=LabelEncoder()
y=lb.fit_transform(y)
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1], dtype=int64)

#splitting the data into train and test

In [59]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=0)

In [60]:
x_test.shape

(2, 4)

In [61]:
x_train

array([[1.0, 0.0, 40.0, 63777.77777777778],
       [0.0, 0.0, 37.0, 67000.0],
       [0.0, 1.0, 27.0, 48000.0],
       [0.0, 1.0, 39.0, 52000.0],
       [0.0, 0.0, 48.0, 79000.0],
       [0.0, 1.0, 38.0, 61000.0],
       [0.0, 0.0, 44.0, 72000.0],
       [0.0, 0.0, 35.0, 58000.0]], dtype=object)

In [62]:
y_train

array([1, 1, 1, 0, 1, 0, 0, 1], dtype=int64)