In [1]:
import numpy
import numpy as np
from numpy import*

In [2]:
z=np.zeros(10)
z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
type(z)

numpy.ndarray

In [4]:
z=np.zeros(10)
z.astype(int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [6]:
z.ndim # to check dimesnsion

1

In [8]:
z=np.array([1,2,3.5,4,64])

In [9]:
z

array([ 1. ,  2. ,  3.5,  4. , 64. ])

In [10]:
z.shape

(5,)

In [11]:
z=np.array([[2,5,6,9],[1,3,5,6]]) #2D array

In [12]:
z

array([[2, 5, 6, 9],
       [1, 3, 5, 6]])

In [13]:
z.ndim

2

In [14]:
z.shape #shape rep rows and columns

(2, 4)

In [15]:
z=z.reshape(4,2)  #reshape the array

In [16]:
z

array([[2, 5],
       [6, 9],
       [1, 3],
       [5, 6]])

In [18]:
z=z.reshape(1,8)
z

array([[2, 5, 6, 9, 1, 3, 5, 6]])

In [20]:
#changing the array into 3 dimension array
z=z.reshape(2,2,2)
z

array([[[2, 5],
        [6, 9]],

       [[1, 3],
        [5, 6]]])

In [22]:
z=z.reshape(8,1,1)
z

array([[[2]],

       [[5]],

       [[6]],

       [[9]],

       [[1]],

       [[3]],

       [[5]],

       [[6]]])

In [23]:
z.ndim

3

In [24]:
z=np.array([[2,5,6,9],[1,3,5,6,8]]) #if the array is not in same, it will form as list

In [25]:
z

array([list([2, 5, 6, 9]), list([1, 3, 5, 6, 8])], dtype=object)

In [26]:
z.ndim

1

In [27]:
z.shape

(2,)

In [28]:
a=np.array([[2,5,6],[6,5,8],[8,9,5]])
a

array([[2, 5, 6],
       [6, 5, 8],
       [8, 9, 5]])

In [34]:
a[1][2]

8

In [30]:
a[[1]]

array([[6, 5, 8]])

In [35]:
a[1:3,1:3]

array([[5, 8],
       [9, 5]])

In [36]:
a[0:2,0:2]

array([[2, 5],
       [6, 5]])

In [37]:
a[0:1,1:3]

array([[5, 6]])

In [41]:
a[1:3,1:2]

array([[5],
       [9]])

In [42]:
b=np.linspace(0,10,20) #equally spaced values btween 0 to 10 and 20 represent the number of elements in the 0 to 10

In [43]:
b

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [46]:
b.max() #maximum value in array

10.0

In [47]:
b.min() #minmum value in array

0.0

In [48]:
b.argmax()

19

In [49]:
b.argmin()

0

In [53]:
b[3:5]

array([1.57894737, 2.10526316])

In [56]:
s=np.arange(100,210,20) #step size of 20 in 100 to 150
s

array([100, 120, 140, 160, 180, 200])

In [57]:
s=s+s


In [58]:
s

array([200, 240, 280, 320, 360, 400])

# Pandas

In [1]:
import pandas as pd

In [2]:
#1. series
#2. DataFrame

In [3]:
mylist=[2,53,60,98]

In [4]:
pd.Series(data=mylist)

0     2
1    53
2    60
3    98
dtype: int64

In [5]:
labels=['A','B','C','D']
pd.Series(data=mylist,index=labels)

A     2
B    53
C    60
D    98
dtype: int64

In [6]:
cricket={'captain':'Virat','opener':'Rohit','keeper':'Dhoni'}
ser1 = pd.Series(cricket)
ser1

captain    Virat
opener     Rohit
keeper     Dhoni
dtype: object

In [7]:
type(ser1)

pandas.core.series.Series

In [8]:
ser3 = pd.Series([1,2,3,4],["India","England","USA","Italy"])
ser3

India      1
England    2
USA        3
Italy      4
dtype: int64

In [9]:
ser4 = pd.Series([5,6,7,8],["England","USA","USA","Italy"])
ser4

England    5
USA        6
USA        7
Italy      8
dtype: int64

In [10]:
ser2 = ser3+ser4

In [11]:
ser2

England     7.0
India       NaN
Italy      12.0
USA         9.0
USA        10.0
dtype: float64

# Dataframe

In [12]:
employees=pd.DataFrame({"Empcode":[1,2,3,4],"Name":["Surya","Vinay","Mahathi","Rammohan"],'Occupation':['ML Engineer','AI Developer','ML ENgineer',"AI Developer"],
                       'Date Of Join':['2018-01-25', '2018-01-26','2018-01-26','2018-01-27'],'Age': [25, 24,24,26]})

In [13]:
employees

Empcode      Name    Occupation Date Of Join  Age
0        1     Surya   ML Engineer   2018-01-25   25
1        2     Vinay  AI Developer   2018-01-26   24
2        3   Mahathi   ML ENgineer   2018-01-26   24
3        4  Rammohan  AI Developer   2018-01-27   26

In [14]:
employees.columns

Index(['Empcode', 'Name', 'Occupation', 'Date Of Join', 'Age'], dtype='object')

In [15]:
employees.columns = ['Empcode', 'EmpName', 'EmpOccupation', 'EmpDate Of Join', 'EmpAge']
employees

Empcode   EmpName EmpOccupation EmpDate Of Join  EmpAge
0        1     Surya   ML Engineer      2018-01-25      25
1        2     Vinay  AI Developer      2018-01-26      24
2        3   Mahathi   ML ENgineer      2018-01-26      24
3        4  Rammohan  AI Developer      2018-01-27      26

In [16]:
employees.drop("Empcode",axis=1,inplace=True)

In [17]:
employees

EmpName EmpOccupation EmpDate Of Join  EmpAge
0     Surya   ML Engineer      2018-01-25      25
1     Vinay  AI Developer      2018-01-26      24
2   Mahathi   ML ENgineer      2018-01-26      24
3  Rammohan  AI Developer      2018-01-27      26

In [18]:
#removing multiple columns using indexing
employees.drop(employees.columns[[0,3]],axis=1)

EmpOccupation EmpDate Of Join
0   ML Engineer      2018-01-25
1  AI Developer      2018-01-26
2   ML ENgineer      2018-01-26
3  AI Developer      2018-01-27

In [19]:
employees

EmpName EmpOccupation EmpDate Of Join  EmpAge
0     Surya   ML Engineer      2018-01-25      25
1     Vinay  AI Developer      2018-01-26      24
2   Mahathi   ML ENgineer      2018-01-26      24
3  Rammohan  AI Developer      2018-01-27      26

In [20]:
#dropping row
employees.drop(2,axis=0)

EmpName EmpOccupation EmpDate Of Join  EmpAge
0     Surya   ML Engineer      2018-01-25      25
1     Vinay  AI Developer      2018-01-26      24
3  Rammohan  AI Developer      2018-01-27      26

In [21]:
employees['Emp City']=["hyderabad","banglore","chennai","delhi"]

In [22]:
employees

EmpName EmpOccupation EmpDate Of Join  EmpAge   Emp City
0     Surya   ML Engineer      2018-01-25      25  hyderabad
1     Vinay  AI Developer      2018-01-26      24   banglore
2   Mahathi   ML ENgineer      2018-01-26      24    chennai
3  Rammohan  AI Developer      2018-01-27      26      delhi

In [23]:
employees.insert(loc=0,column="Surname",value=["M","N","O","P"])

In [65]:
employees

Surname   EmpName EmpOccupation EmpDate Of Join  EmpAge   Emp City
0       M     Surya   ML Engineer      2018-01-25      25  hyderabad
1       N     Vinay  AI Developer      2018-01-26      24   banglore
2       O   Mahathi   ML ENgineer      2018-01-26      24    chennai
3       P  Rammohan  AI Developer      2018-01-27      26      delhi
4       B     Mohan      Engineer      2018-01-26      26     Mumbai

In [67]:
employees.iloc[2:,2:4] #index location (iloc)

EmpOccupation EmpDate Of Join
2   ML ENgineer      2018-01-26
3  AI Developer      2018-01-27
4      Engineer      2018-01-26

In [24]:
employees

Surname   EmpName EmpOccupation EmpDate Of Join  EmpAge   Emp City
0       M     Surya   ML Engineer      2018-01-25      25  hyderabad
1       N     Vinay  AI Developer      2018-01-26      24   banglore
2       O   Mahathi   ML ENgineer      2018-01-26      24    chennai
3       P  Rammohan  AI Developer      2018-01-27      26      delhi

In [25]:
new={"Surname":"B","EmpName":"Mohan","EmpOccupation":"Engineer","EmpDate Of Join":"2018-01-26","EmpAge":26,"Emp City":"Mumbai"}

In [34]:
employees = employees.append(new,ignore_index=True)

In [35]:
z=employees.values

In [36]:
z

array([['M', 'Surya', 'ML Engineer', '2018-01-25', 25, 'hyderabad'],
       ['N', 'Vinay', 'AI Developer', '2018-01-26', 24, 'banglore'],
       ['O', 'Mahathi', 'ML ENgineer', '2018-01-26', 24, 'chennai'],
       ['P', 'Rammohan', 'AI Developer', '2018-01-27', 26, 'delhi'],
       ['B', 'Mohan', 'Engineer', '2018-01-26', 26, 'Mumbai']],
      dtype=object)

In [37]:
df=pd.DataFrame(z)
df

0         1             2           3   4          5
0  M     Surya   ML Engineer  2018-01-25  25  hyderabad
1  N     Vinay  AI Developer  2018-01-26  24   banglore
2  O   Mahathi   ML ENgineer  2018-01-26  24    chennai
3  P  Rammohan  AI Developer  2018-01-27  26      delhi
4  B     Mohan      Engineer  2018-01-26  26     Mumbai

# loading a dataset

In [38]:
import pandas as pd

In [40]:
dataset=pd.read_csv(r'Salaries.csv')

In [43]:
dataset

Id            EmployeeName  \
0            1          NATHANIEL FORD   
1            2            GARY JIMENEZ   
2            3          ALBERT PARDINI   
3            4       CHRISTOPHER CHONG   
4            5         PATRICK GARDNER   
5            6          DAVID SULLIVAN   
6            7               ALSON LEE   
7            8           DAVID KUSHNER   
8            9          MICHAEL MORRIS   
9           10      JOANNE HAYES-WHITE   
10          11           ARTHUR KENNEY   
11          12        PATRICIA JACKSON   
12          13       EDWARD HARRINGTON   
13          14             JOHN MARTIN   
14          15          DAVID FRANKLIN   
15          16         RICHARD CORRIEA   
16          17                AMY HART   
17          18          SEBASTIAN WONG   
18          19              MARTY ROSS   
19          20           ELLEN MOFFATT   
20          21              VENUS AZAR   
21          22            JUDY MELINEK   
22          23           GEORGE GARCIA   
23          24           VICTOR WYRSCH   
24          25         JOSEPH DRISCOLL   
25          26            GREGORY SUHR   
26          27             JOHN HANLEY   
27          28          RAYMOND GUZMAN   
28          29          DENISE SCHMITT   
29          30           MONICA FIELDS   
...        ...                     ...   
148624  148625      Lorraine Rosenthal   
148625  148626         Renato C Gurion   
148626  148627           Paulet Gaines   
148627  148628        Brett A Lundberg   
148628  148629          Mark W Mcclure   
148629  148630       Elizabeth Iniguez   
148630  148631            Randy J Keys   
148631  148632         Andre M Johnson   
148632  148633  Sharon D Owens-Webster   
148633  148634        Edward Ferdinand   
148634  148635          David M Turner   
148635  148636     James S Kibblewhite   
148636  148637           Andrew J Enzi   
148637  148638        Kadeshra D Green   
148638  148639    Lennard B Hutchinson   
148639  148640       Richard A Talbert   
148640  148641      Charlene D Mccully   
148641  148642   Raphael Marquis Goins   
148642  148643       Dominic C Marquez   
148643  148644              Kim Brewer   
148644  148645            Randy D Winn   
148645  148646        Carolyn A Wilson   
148646  148647            Not provided   
148647  148648          Joann Anderson   
148648  148649             Leon Walker   
148649  148650           Roy I Tillery   
148650  148651            Not provided   
148651  148652            Not provided   
148652  148653            Not provided   
148653  148654               Joe Lopez   

                                                JobTitle       BasePay  \
0         GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY        167411   
1                        CAPTAIN III (POLICE DEPARTMENT)        155966   
2                        CAPTAIN III (POLICE DEPARTMENT)        212739   
3                   WIRE ROPE CABLE MAINTENANCE MECHANIC         77916   
4           DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)        134402   
5                              ASSISTANT DEPUTY CHIEF II        118602   
6                     BATTALION CHIEF, (FIRE DEPARTMENT)         92492   
7                         DEPUTY DIRECTOR OF INVESTMENTS        256577   
8                     BATTALION CHIEF, (FIRE DEPARTMENT)        176933   
9                 CHIEF OF DEPARTMENT, (FIRE DEPARTMENT)        285262   
10      ASSISTANT CHIEF OF DEPARTMENT, (FIRE DEPARTMENT)        194999   
11                       CAPTAIN III (POLICE DEPARTMENT)         99722   
12                           EXECUTIVE CONTRACT EMPLOYEE        294580   
13                                     DEPARTMENT HEAD V        271329   
14                    BATTALION CHIEF, (FIRE DEPARTMENT)        174873   
15                    COMMANDER III, (POLICE DEPARTMENT)        198778   
16                                     DEPARTMENT HEAD V        268605   
17                 CAPTAIN, EMERGENCYCY MEDICAL SERVICES        140547   
1

In [44]:
dataset.head()

Id       EmployeeName                                        JobTitle  \
0   1     NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1   2       GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   
2   3     ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)   
3   4  CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC   
4   5    PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   

  BasePay OvertimePay OtherPay Benefits   TotalPay  TotalPayBenefits  Year  \
0  167411           0   400184      NaN  567595.43         567595.43  2011   
1  155966      245132   137811      NaN  538909.28         538909.28  2011   
2  212739      106088  16452.6      NaN  335279.91         335279.91  2011   
3   77916     56120.7   198307      NaN  332343.61         332343.61  2011   
4  134402        9737   182235      NaN  326373.19         326373.19  2011   

   Notes         Agency Status  
0    NaN  San Francisco    NaN  
1    NaN  San Francisco    NaN  
2    NaN  San Francisco    NaN  
3    NaN  San Francisco    NaN  
4    NaN  San Francisco    NaN

In [45]:
dataset.tail()

Id   EmployeeName                    JobTitle       BasePay  \
148649  148650  Roy I Tillery                   Custodian          0.00   
148650  148651   Not provided                Not provided  Not Provided   
148651  148652   Not provided                Not provided  Not Provided   
148652  148653   Not provided                Not provided  Not Provided   
148653  148654      Joe Lopez  Counselor, Log Cabin Ranch          0.00   

         OvertimePay      OtherPay      Benefits  TotalPay  TotalPayBenefits  \
148649          0.00          0.00          0.00      0.00              0.00   
148650  Not Provided  Not Provided  Not Provided      0.00              0.00   
148651  Not Provided  Not Provided  Not Provided      0.00              0.00   
148652  Not Provided  Not Provided  Not Provided      0.00              0.00   
148653          0.00       -618.13          0.00   -618.13           -618.13   

        Year  Notes         Agency Status  
148649  2014    NaN  San Francisco     PT  
148650  2014    NaN  San Francisco    NaN  
148651  2014    NaN  San Francisco    NaN  
148652  2014    NaN  San Francisco    NaN  
148653  2014    NaN  San Francisco     PT

In [46]:
type(dataset)

pandas.core.frame.DataFrame

In [47]:
dataset.describe()

Id       TotalPay  TotalPayBenefits           Year  Notes
count  148654.000000  148654.000000     148654.000000  148654.000000    0.0
mean    74327.500000   74768.321972      93692.554811    2012.522643    NaN
std     42912.857795   50517.005274      62793.533483       1.117538    NaN
min         1.000000    -618.130000       -618.130000    2011.000000    NaN
25%     37164.250000   36168.995000      44065.650000    2012.000000    NaN
50%     74327.500000   71426.610000      92404.090000    2013.000000    NaN
75%    111490.750000  105839.135000     132876.450000    2014.000000    NaN
max    148654.000000  567595.430000     567595.430000    2014.000000    NaN

In [52]:
dataset.isnull().any()  #for checking null values

Id                  False
EmployeeName        False
JobTitle            False
BasePay              True
OvertimePay         False
OtherPay            False
Benefits             True
TotalPay            False
TotalPayBenefits    False
Year                False
Notes                True
Agency              False
Status               True
dtype: bool

In [53]:
#checking null values in specific column
dataset["Notes"].isnull()

0         True
1         True
2         True
3         True
4         True
5         True
6         True
7         True
8         True
9         True
10        True
11        True
12        True
13        True
14        True
15        True
16        True
17        True
18        True
19        True
20        True
21        True
22        True
23        True
24        True
25        True
26        True
27        True
28        True
29        True
          ... 
148624    True
148625    True
148626    True
148627    True
148628    True
148629    True
148630    True
148631    True
148632    True
148633    True
148634    True
148635    True
148636    True
148637    True
148638    True
148639    True
148640    True
148641    True
148642    True
148643    True
148644    True
148645    True
148646    True
148647    True
148648    True
148649    True
148650    True
148651    True
148652    True
148653    True
Name: Notes, Length: 148654, dtype: bool

In [55]:
dataset[dataset['BasePay'].isnull()].index.tolist()  #index position of nul values using like this

[81391,
 84506,
 84960,
 90525,
 90786,
 90811,
 91203,
 92260,
 97418,
 98573,
 100464,
 101190,
 101596,
 101792,
 101843,
 101899,
 101952,
 102046,
 102199,
 102226,
 102303,
 102995,
 103069,
 103121,
 103139,
 103457,
 103561,
 103828,
 103852,
 103868,
 103872,
 103907,
 103951,
 103960,
 103979,
 104036,
 104045,
 104094,
 104097,
 104162,
 104221,
 104233,
 104278,
 104343,
 104349,
 104396,
 104410,
 104448,
 104495,
 104533,
 104607,
 104619,
 104633,
 104728,
 104729,
 104780,
 104810,
 104863,
 104985,
 105005,
 105011,
 105021,
 105022,
 105036,
 105099,
 105118,
 105128,
 105192,
 105230,
 105248,
 105280,
 105300,
 105317,
 105327,
 105336,
 105339,
 105369,
 105370,
 105425,
 105427,
 105495,
 105505,
 105507,
 105515,
 105531,
 105555,
 105616,
 105641,
 105647,
 105655,
 105657,
 105676,
 105709,
 105720,
 105723,
 105751,
 105807,
 105819,
 105892,
 105913,
 105932,
 105974,
 105991,
 106031,
 106058,
 106071,
 106083,
 106138,
 106180,
 106190,
 106265,
 106272,
 1

In [57]:
dataset.isnull().sum() #count of null values

Id                       0
EmployeeName             0
JobTitle                 0
BasePay                605
OvertimePay              0
OtherPay                 0
Benefits             36159
TotalPay                 0
TotalPayBenefits         0
Year                     0
Notes               148654
Agency                   0
Status              110535
dtype: int64

In [62]:
dataset.sort_values(by="TotalPayBenefits",ascending=False)['EmployeeName'].iloc[0]  #higest pay earning 

'NATHANIEL FORD'

In [64]:
dataset[dataset['EmployeeName']=="NATHANIEL FORD"]["BasePay"]

0    167411
Name: BasePay, dtype: object

In [68]:
data = {'Company':['GOOG','GOOG','MSFT','MSFT','FB','FB'],
       'Person':['Sam','Charlie','Amy','Vanessa','Carl','Sarah'],
       'Sales':[200,120,340,124,243,350]}

In [69]:
df=pd.DataFrame(data)
df

Company   Person  Sales
0    GOOG      Sam    200
1    GOOG  Charlie    120
2    MSFT      Amy    340
3    MSFT  Vanessa    124
4      FB     Carl    243
5      FB    Sarah    350

In [72]:
by_comp = df.groupby("Company")
by_comp

In [73]:
by_comp.mean()

Sales
Company       
FB       296.5
GOOG     160.0
MSFT     232.0

In [74]:
by_comp.describe()

Sales                                                        
        count   mean         std    min     25%    50%     75%    max
Company                                                              
FB        2.0  296.5   75.660426  243.0  269.75  296.5  323.25  350.0
GOOG      2.0  160.0   56.568542  120.0  140.00  160.0  180.00  200.0
MSFT      2.0  232.0  152.735065  124.0  178.00  232.0  286.00  340.0

In [75]:
by_comp.max()

Person  Sales
Company                
FB         Sarah    350
GOOG         Sam    200
MSFT     Vanessa    340